config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # get 'restaurants', to: 'restaurants#index'
  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
  # get 'restaurants/new', to: 'restaurants#new', as: :restaurant_new
  # post 'restaurants', to: 'restaurants#create'
  # get 'restaurants', to: 'restaurants#index'

  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params_restaurants)
    if @restaurant.save!
      redirect_to @restaurant
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(params_restaurants)
      redirect_to @restaurant
    else
      render :index
    end
  end

  def destroy
   if @restaurant.destroy
    redirect_to restaurants_path
   end
  end

  private

  def params_restaurants
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%= form_with model: @restaurant do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :address %>
  <%= form.number_field :rating %>
  <%= form.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Hello world, voici les meilleurds restaurants près de chez toi</h1>
<%= link_to 'Créer un restooooo', new_restaurant_path, class: 'btn btn-success text-white' %>
<% @restaurants.each do |restaurant| %>
<div class="bg-light w-25  p-5 m-2 rounded">
  <p><%= restaurant.name %></p>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.rating %>/5</p>
  <%= link_to 'Voir le restaurant', restaurant_path(restaurant.id), class: 'btn btn-primary' %>
</div>
<% end %>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>

<%= form_with model: @restaurant do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :address %>
  <%= form.number_field :rating %>
  <%= form.submit %>
<% end %>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.rating %>/5</p>
<%= link_to "Supprimer le restaurant #{@restaurant.name}", restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
<%=link_to 'Edit the restaurant', edit_restaurant_path(@restaurant), class: 'btn btn-info' %>